@"
FROM python:3.12-slim

WORKDIR /app

COPY requirement.txt .

RUN pip install --no-cache-dir -r requirement.txt

COPY app.py .
COPY services ./services
COPY static ./static
COPY templates ./templates

EXPOSE 5000

CMD ["python", "app.py"]
"@ | Set-Content Dockerfile